Repository marcosdosea/ModernSchool, pull requests merged in 2022-09, with the labels that each got.

#49 Relacionamento comunicação com professor de 1:n com aluno e componente.
  AnaliseProjeto/CasoDeUsoEscolaAnalise.mdj
Labels: enhancement

#69 resolve #68 Mudando papel Diretor para Servidor
  AnaliseProjeto/CasoDeUsoEscolaAnalise.mdj
Labels: enhancement

#71 O atributo diretor adicionado a entidade escola. fixed #70
  AnaliseProjeto/CasoDeUsoEscolaAnalise.mdj
Labels: enhancement

#80 campos fundamental, infantil e médio na entidade currículo, alterado …
  AnaliseProjeto/CasoDeUsoEscolaAnalise.mdj
Labels: documentation

#83 DER do staruml com os relacionamentos atualizados. #79
  AnaliseProjeto/CasoDeUsoEscolaAnalise.mdj
Labels: documentation, enhancement

#84 processo de interactioMatricula concluido. #76
  AnaliseProjeto/CasoDeUsoEscolaAnalise.mdj
Labels: documentation

#86 tabelas mapeadas para o mysql. #85
  AnaliseProjeto/ModernSchool.mwb
  AnaliseProjeto/ModernSchool.mwb.bak
Labels: documentation, enhancement

#94 relacionamento feitos, ficou faltando ver a questão do aluno, não sei…
  AnaliseProjeto/ModernSchool.mwb
  AnaliseProjeto/ModernSchool.mwb.bak
Labels: documentation, enhancement

#96 relacionamentos consertados. comunicacao professor, turma se relacion…
  AnaliseProjeto/CasoDeUsoEscolaAnalise.mdj
Labels: documentation, enhancement

#127 Adicionando documento em Gerenciamento "Exemplo Guia Análise e Projet…
  Gerenciamento/Exemplo Guia Análise e Projeto.docx
Labels: documentation, enhancement

#132 upando o mapeamento feito do der do staruml para o mysql. #130
  AnaliseProjeto/ModernSchool.mwb
  AnaliseProjeto/ModernSchool.mwb.bak
Labels: documentation, enhancement

#133 Adicionado o Documento de Arquitetura #131
  Gerenciamento/Documento de Arquitetura.docx
  Gerenciamento/Guia Análise e Projeto.docx
Labels: documentation, enhancement

#152 Solicito revisão da criação das classes a partir do BD
  AnaliseProjeto/ModernSchool.mwb
  AnaliseProjeto/ModernSchool.mwb.bak
  Codigo/ModernSchool/.vs/ModernSchool/DesignTimeBuild/.dtbcache.v2
  Codigo/ModernSchool/.vs/ModernSchool/FileContentIndex/0b9977ab-72ab-4b01-99df-432f202eaead.vsidx
  Codigo/ModernSchool/.vs/ModernSchool/FileContentIndex/1fcae5cd-b39f-4047-9478-a38cf9517c9b.vsidx
  Codigo/ModernSchool/.vs/ModernSchool/FileContentIndex/bfce4a48-9a61-482c-88ac-424d86fb7c5b.vsidx
  Codigo/ModernSchool/.vs/ModernSchool/FileContentIndex/ff9d5381-def7-4abc-b9ec-5a19a0a2e145.vsidx
  Codigo/ModernSchool/.vs/ModernSchool/v17/.suo
  Codigo/ModernSchool/.vs/ProjectEvaluation/modernschool.metadata.v5
  Codigo/ModernSchool/.vs/ProjectEvaluation/modernschool.metadata.v5.1
  Codigo/ModernSchool/.vs/ProjectEvaluation/modernschool.projects.v5
  Codigo/ModernSchool/.vs/ProjectEvaluation/modernschool.projects.v5.1
  Codigo/ModernSchool/Core/Alunoavaliacao.cs
  Codigo/ModernSchool/Core/Alunocomunicacao.cs
  Codigo/ModernSchool/Core/Anoletivo.cs
  Codigo/ModernSchool/Core/Avaliacao.cs
  Codigo/ModernSchool/Core/Cargo.cs
  Codigo/ModernSchool/Core/Componente.cs
  Codigo/ModernSchool/Core/Comunicacao.cs
  Codigo/ModernSchool/Core/Core.csproj
  Codigo/ModernSchool/Core/Curriculo.cs
  Codigo/ModernSchool/Core/Diariodeclasse.cs
  Codigo/ModernSchool/Core/Escola.cs
  Codigo/ModernSchool/Core/Frequenciaaluno.cs
  Codigo/ModernSchool/Core/Governo.cs
  Codigo/ModernSchool/Core/Governoservidor.cs
  Codigo/ModernSchool/Core/Gradehorario.cs
  Codigo/ModernSchool/Core/Habilidade.cs
  Codigo/ModernSchool/Core/ModernSchoolContext.cs
  Codigo/ModernSchool/Core/Objetodeconhecimento.cs
  Codigo/ModernSchool/Core/Objetodeconhecimentodiariodeclasse.cs
  Codigo/ModernSchool/Core/Periodo.cs
  Codigo/ModernSchool/Core/Pessoa.cs
  Codigo/ModernSchool/Core/Pessoacomunicacao.cs
  Codigo/ModernSchool/Core/Turma.cs
  Codigo/ModernSchool/Core/Unidadetematica.cs
  Codigo/ModernSchool/ModernSchool.sln
Labels: documentation, enhancement

#178 Manter cargo implementado #169
  Codigo/ModernSchool/.vs/ModernSchool/DesignTimeBuild/.dtbcache.v2
  Codigo/ModernSchool/.vs/ModernSchool/v17/.futdcache.v2
  Codigo/ModernSchool/.vs/ModernSchool/v17/.suo
  Codigo/ModernSchool/.vs/ProjectEvaluation/modernschool.metadata.v5.1
  Codigo/ModernSchool/.vs/ProjectEvaluation/modernschool.projects.v5.1
  Codigo/ModernSchool/Core/Service/ICargoService.cs
  Codigo/ModernSchool/Core/Service/ICurriculoService.cs
  Codigo/ModernSchool/ModernSchool/Controllers/CargoController.cs
  Codigo/ModernSchool/ModernSchool/Controllers/CurriculoController.cs
  Codigo/ModernSchool/ModernSchool/Mappers/CargoProfile.cs
  Codigo/ModernSchool/ModernSchool/Mappers/CurriculoProfile.cs
  Codigo/ModernSchool/ModernSchool/Models/CargoViewModel.cs
  Codigo/ModernSchool/ModernSchool/Models/CurriculoViewModel.cs
  Codigo/ModernSchool/ModernSchool/Program.cs
  Codigo/ModernSchool/ModernSchool/Views/Cargo/Create.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Cargo/Delete.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Cargo/Details.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Cargo/Edit.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Cargo/Index.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Curriculo/Create.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Curriculo/Delete.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Curriculo/Details.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Curriculo/Edit.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Curriculo/Index.cshtml
  Codigo/ModernSchool/Service/CargoService.cs
  Codigo/ModernSchool/Service/CurriculoService.cs
Labels: enhancement, code

#180 Branch matheus166
  Codigo/ModernSchool/.vs/ModernSchool/DesignTimeBuild/.dtbcache.v2
  Codigo/ModernSchool/.vs/ModernSchool/v17/.futdcache.v2
  Codigo/ModernSchool/.vs/ModernSchool/v17/.suo
  Codigo/ModernSchool/.vs/ProjectEvaluation/modernschool.metadata.v5.1
  Codigo/ModernSchool/.vs/ProjectEvaluation/modernschool.projects.v5.1
  Codigo/ModernSchool/.vs/VSWorkspaceState.json
  Codigo/ModernSchool/.vs/slnx.sqlite
  Codigo/ModernSchool/Core/Service/IGovernoService.cs
  Codigo/ModernSchool/ModernSchool/Controllers/GovernoController.cs
  Codigo/ModernSchool/ModernSchool/Mappers/GovernoProfile.cs
  Codigo/ModernSchool/ModernSchool/Models/GovernoViewModel.cs
  Codigo/ModernSchool/ModernSchool/ModernSchool.csproj
  Codigo/ModernSchool/ModernSchool/Program.cs
  Codigo/ModernSchool/ModernSchool/Views/Governo/Create.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Governo/Delete.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Governo/Details.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Governo/Edit.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Governo/Index.cshtml
  Codigo/ModernSchool/Service/GovernoService.cs
Labels: enhancement, code
