Repository marcosdosea/ModernSchool, pull requests merged in 2022-10, with the labels that each got.

#182 Projeto atualizado.
  Codigo/ModernSchool/.vs/ModernSchool/DesignTimeBuild/.dtbcache.v2
  Codigo/ModernSchool/.vs/ModernSchool/v17/.futdcache.v2
  Codigo/ModernSchool/.vs/ModernSchool/v17/.suo
  Codigo/ModernSchool/.vs/ProjectEvaluation/modernschool.metadata.v5.1
  Codigo/ModernSchool/.vs/ProjectEvaluation/modernschool.projects.v5.1
  Codigo/ModernSchool/ModernSchool.sln
  Codigo/ModernSchool/ModernSchool/Controllers/AvaliacaoController.cs
  Codigo/ModernSchool/ModernSchool/Controllers/CargoController.cs
  Codigo/ModernSchool/ModernSchool/Controllers/ComponenteController.cs
  Codigo/ModernSchool/ModernSchool/Controllers/CurriculoController.cs
  Codigo/ModernSchool/ModernSchool/Controllers/GovernoController.cs
  Codigo/ModernSchool/ModernSchool/Controllers/HomeController.cs
  Codigo/ModernSchool/ModernSchool/Mappers/AvaliacaoProfile.cs
  Codigo/ModernSchool/ModernSchool/Mappers/CargoProfile.cs
  Codigo/ModernSchool/ModernSchool/Mappers/ComponenteProfile.cs
  Codigo/ModernSchool/ModernSchool/Mappers/CurriculoProfile.cs
  Codigo/ModernSchool/ModernSchool/Models/AvaliacaoViewModel.cs
  Codigo/ModernSchool/ModernSchool/Models/CargoViewModel.cs
  Codigo/ModernSchool/ModernSchool/Models/ComponenteViewModel.cs
  Codigo/ModernSchool/ModernSchool/Models/CurriculoViewModel.cs
  Codigo/ModernSchool/ModernSchool/Models/ErrorViewModel.cs
  Codigo/ModernSchool/ModernSchool/ModernSchool.csproj
  Codigo/ModernSchool/ModernSchool/ModernSchoolWEB.csproj
  Codigo/ModernSchool/ModernSchool/Program.cs
  Codigo/ModernSchool/ModernSchool/Views/Avaliacao/Create.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Avaliacao/Delete.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Avaliacao/Details.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Avaliacao/Edit.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Avaliacao/Index.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Cargo/Create.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Cargo/Delete.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Cargo/Details.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Cargo/Edit.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Cargo/Index.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Componente/Create.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Componente/Delete.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Componente/Details.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Componente/Edit.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Componente/Index.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Curriculo/Create.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Curriculo/Delete.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Curriculo/Details.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Curriculo/Edit.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Curriculo/Index.cshtml
  Codigo/ModernSchool/ModernSchool/Views/_ViewImports.cshtml
  Codigo/ModernSchool/Service/CargoService.cs
Labels: code

#183 Branch moises179
  Codigo/ModernSchool/Core/Anoletivo.cs
  Codigo/ModernSchool/Core/ModernSchoolContext.cs
  Codigo/ModernSchool/Core/Service/IAnoLetivoService.cs
  Codigo/ModernSchool/ModernSchool/Controllers/AnoLetivoController.cs
  Codigo/ModernSchool/ModernSchool/Mappers/AnoLetivoProfile.cs
  Codigo/ModernSchool/ModernSchool/Models/AnoLetivoViewModel.cs
  Codigo/ModernSchool/ModernSchool/Views/AnoLetivo/Create.cshtml
  Codigo/ModernSchool/ModernSchool/Views/AnoLetivo/Delete.cshtml
  Codigo/ModernSchool/ModernSchool/Views/AnoLetivo/Details.cshtml
  Codigo/ModernSchool/ModernSchool/Views/AnoLetivo/Edit.cshtml
  Codigo/ModernSchool/ModernSchool/Views/AnoLetivo/Index.cshtml
  Codigo/ModernSchool/Service/AnoLetivoService.cs
Labels: enhancement, code

#185 Branch reinan184
  .gitignore
  Codigo/ModernSchool/.vs/ModernSchool/DesignTimeBuild/.dtbcache.v2
  Codigo/ModernSchool/.vs/ModernSchool/FileContentIndex/read.lock
  Codigo/ModernSchool/.vs/ModernSchool/config/applicationhost.config
  Codigo/ModernSchool/.vs/ModernSchool/v17/.futdcache.v2
  Codigo/ModernSchool/.vs/ModernSchool/v17/.suo
  Codigo/ModernSchool/.vs/ProjectEvaluation/modernschool.metadata.v5.1
  Codigo/ModernSchool/.vs/ProjectEvaluation/modernschool.projects.v5.1
  Codigo/ModernSchool/.vs/VSWorkspaceState.json
  Codigo/ModernSchool/.vs/slnx.sqlite
  Codigo/ModernSchool/ModernSchool/ModernSchool.csproj
  Codigo/ModernSchool/ModernSchool/Program.cs
Labels: bug

#187 implementado caso de uso turma
  Codigo/ModernSchool/Core/Service/ITurmaService.cs
  Codigo/ModernSchool/ModernSchool/Controllers/ComponenteController.cs
  Codigo/ModernSchool/ModernSchool/Controllers/TurmaController.cs
  Codigo/ModernSchool/ModernSchool/Mappers/AvaliacaoProfile.cs
  Codigo/ModernSchool/ModernSchool/Mappers/TurmaProfile.cs
  Codigo/ModernSchool/ModernSchool/Models/TurmaViewModel.cs
  Codigo/ModernSchool/ModernSchool/Program.cs
  Codigo/ModernSchool/ModernSchool/Views/Turma/Create.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Turma/Delete.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Turma/Details.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Turma/Edit.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Turma/Index.cshtml
  Codigo/ModernSchool/Service/TurmaService.cs
Labels: enhancement, code

#190 Caso de uso Manter comunicacao criado. resolve #162
  Codigo/ModernSchool/Core/ModernSchoolContext.cs
  Codigo/ModernSchool/Core/Service/IComunicacaoService.cs
  Codigo/ModernSchool/ModernSchool/Controllers/ComunicacaoController.cs
  Codigo/ModernSchool/ModernSchool/Controllers/PeriodoController.cs
  Codigo/ModernSchool/ModernSchool/Mappers/ComunicacaoProfile.cs
  Codigo/ModernSchool/ModernSchool/Mappers/CurriculoProfile.cs
  Codigo/ModernSchool/ModernSchool/Models/AvaliacaoViewModel.cs
  Codigo/ModernSchool/ModernSchool/Models/ComunicacaoViewModel.cs
  Codigo/ModernSchool/ModernSchool/Models/GovernoViewModel.cs
  Codigo/ModernSchool/ModernSchool/Models/PeriodoViewModel.cs
  Codigo/ModernSchool/ModernSchool/Models/TurmaViewModel.cs
  Codigo/ModernSchool/ModernSchool/Program.cs
  Codigo/ModernSchool/ModernSchool/Views/Comunicacao/Create.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Comunicacao/Delete.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Comunicacao/Details.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Comunicacao/Edit.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Comunicacao/Index.cshtml
  Codigo/ModernSchool/Service/CargoService.cs
  Codigo/ModernSchool/Service/ComunicacaoService.cs
Labels: bug, enhancement, code

#193 Removendo o .vs do projeto.
  Codigo/ModernSchool/.vs/ModernSchool/DesignTimeBuild/.dtbcache.v2
  Codigo/ModernSchool/.vs/ModernSchool/v17/.futdcache.v2
  Codigo/ModernSchool/.vs/ModernSchool/v17/.suo
  Codigo/ModernSchool/.vs/ProjectEvaluation/modernschool.metadata.v5.1
  Codigo/ModernSchool/.vs/ProjectEvaluation/modernschool.projects.v5.1
Labels: bug

#202 UC-Manter escola implementada
  Codigo/ModernSchool/Core/Service/IEscolaService.cs
  Codigo/ModernSchool/ModernSchool/Controllers/EscolaController.cs
  Codigo/ModernSchool/ModernSchool/Mappers/EscolaProfile.cs
  Codigo/ModernSchool/ModernSchool/Models/EscolaViewModel.cs
  Codigo/ModernSchool/ModernSchool/Program.cs
  Codigo/ModernSchool/ModernSchool/Views/Escola/Create.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Escola/Delete.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Escola/Details.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Escola/Edit.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Escola/Index.cshtml
Labels: enhancement, code

#206 Atualizando botoes de excluir das Tela_023 e Tela_029.PNG, pois não e…
  Requisitos/Modern school att.fig
  Requisitos/TelaAdm/Manter Turma/Tela_023.PNG
  Requisitos/TelaAdm/Manter Turma/Tela_029.PNG
Labels: documentation, enhancement

#208 adicionado campos requeridos na ViewModel AnoLetivo e Periodo. #207
  Codigo/ModernSchool/ModernSchool/Models/AnoLetivoViewModel.cs
  Codigo/ModernSchool/ModernSchool/Models/PeriodoViewModel.cs
Labels: enhancement, code

#215 Validações adicionadas no UC- Manter escola, UC-Manter AnoLetivo, UC-Manter Periodo
  Codigo/ModernSchool/ModernSchool/Models/AnoLetivoViewModel.cs
  Codigo/ModernSchool/ModernSchool/Models/EscolaViewModel.cs
  Codigo/ModernSchool/ModernSchool/Models/PeriodoViewModel.cs
Labels: enhancement, code

#217 Adicionado Projeto ModernSchoolWebTest e ServiceTest
  Codigo/ModernSchool/ModernSchool.sln
  Codigo/ModernSchool/ModernSchoolWEBTests/Controllers/AnoLetivoControllerTests.cs
  Codigo/ModernSchool/ModernSchoolWEBTests/ModernSchoolWEBTests.csproj
  Codigo/ModernSchool/ServiceTests/AnoLetivoServiceTests.cs
  Codigo/ModernSchool/ServiceTests/ServiceTests.csproj
Labels: enhancement, code

#227 Campos requeridos, display name e error string length
  Codigo/ModernSchool/ModernSchool/Models/CargoViewModel.cs
  Codigo/ModernSchool/ModernSchool/Models/ComunicacaoViewModel.cs
  Codigo/ModernSchool/ModernSchool/Models/CurriculoViewModel.cs
Labels: enhancement, code, 4.0

#235 DTO adicionado no Core
  Codigo/ModernSchool/Core/DTO/EscolaProfessorDTO.cs
  Codigo/ModernSchool/ModernSchool/Mappers/EscolaProfessorDTOProfile.cs
  Codigo/ModernSchool/ModernSchool/Models/EscolaProfessorDTOViewModel.cs
Labels: bug

#231 Implementado caso de uso UnidadeTematica
  Codigo/ModernSchool/Core/Service/IUnidadeTematicaService.cs
  Codigo/ModernSchool/ModernSchool/Controllers/UnidadeTematicaController.cs
  Codigo/ModernSchool/ModernSchool/Mappers/UnidadeTematicaProfile.cs
  Codigo/ModernSchool/ModernSchool/Models/ComponenteViewModel.cs
  Codigo/ModernSchool/ModernSchool/Models/UnidadeTematicaViewModel.cs
  Codigo/ModernSchool/ModernSchool/ModernSchoolWEB.csproj
  Codigo/ModernSchool/ModernSchool/Program.cs
  Codigo/ModernSchool/ModernSchool/Views/UnidadeTematica/Create.cshtml
  Codigo/ModernSchool/ModernSchool/Views/UnidadeTematica/Delete.cshtml
  Codigo/ModernSchool/ModernSchool/Views/UnidadeTematica/Details.cshtml
  Codigo/ModernSchool/ModernSchool/Views/UnidadeTematica/Edit.cshtml
  Codigo/ModernSchool/ModernSchool/Views/UnidadeTematica/Index.cshtml
  Codigo/ModernSchool/Service/UnidadeTematicaService.cs
Labels: enhancement, code, 4.0

#238 Implementado testes no caso de uso Componente
  Codigo/ModernSchool/ModernSchoolWEBTests/Controllers/ComponenteControllerTests.cs
  Codigo/ModernSchool/ServiceTests/ComponenteServiceTests.cs
Labels: enhancement, code, 4.0

#241 Teste de unidade para Classe service e controller implementado
  Codigo/ModernSchool/ModernSchool/Controllers/ComunicacaoController.cs
  Codigo/ModernSchool/ModernSchoolWEBTests/Controllers/ComunicacaoControllerTests.cs
  Codigo/ModernSchool/ServiceTests/ComunicacaoServiceTests.cs
Labels: enhancement, code, 4.0

#246 Branch samuel158
  Codigo/ModernSchool/Core/Service/IPessoaService.cs
  Codigo/ModernSchool/ModernSchool/Controllers/PessoaController.cs
  Codigo/ModernSchool/ModernSchool/Mappers/PessoaProfile.cs
  Codigo/ModernSchool/ModernSchool/Models/PessoaViewModel.cs
  Codigo/ModernSchool/ModernSchool/Program.cs
  Codigo/ModernSchool/ModernSchool/Views/Pessoa/Create.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Pessoa/Delete.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Pessoa/Details.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Pessoa/Edit.cshtml
  Codigo/ModernSchool/ModernSchool/Views/Pessoa/Index.cshtml
  Codigo/ModernSchool/Service/PessoaService.cs
Labels: documentation, code, 4.0

#249 Alteração concluída no caso de uso governo #248
  Codigo/ModernSchool/ModernSchool/Models/GovernoViewModel.cs
  Codigo/ModernSchool/ModernSchool/Views/Governo/Create.cshtml
Labels: enhancement, code, 4.0

#261 Implementados testes de UC-Manter Escola
  Codigo/ModernSchool/ModernSchool/Controllers/EscolaController.cs
  Codigo/ModernSchool/ModernSchoolWEBTests/Controllers/EscolaControllerTests.cs
  Codigo/ModernSchool/ServiceTests/EscolaServiceTests.cs
Labels: enhancement, code, 5.0

#264 Concertando o campo data do caso de uso pessoa. resolve #263
  Codigo/ModernSchool/ModernSchool/Models/AnoLetivoViewModel.cs
  Codigo/ModernSchool/ModernSchool/Models/PessoaViewModel.cs
Labels: enhancement, 5.0
