Repository marcosdosea/ModernSchool, pull requests merged in 2023-03, with the labels that each got.

#315 Problema resolvido do teste de unidade da ServiceTests/AvaliacaoServi…
  Codigo/ModernSchool/ServiceTests/AvaliacaoServiceTests.cs
Labels: bug, enhancement, code

#313 Branch matheus312
  Codigo/ModernSchool/ModernSchool/Controllers/AvaliacaoController.cs
  Codigo/ModernSchool/ModernSchoolWEBTests/Controllers/AvaliacaoControllerTests.cs
Labels: bug

#321 Implementaçao de pessoa teste
  Codigo/ModernSchool/ModernSchoolWEBTests/Controllers/PessoaControllerTests.cs
  Codigo/ModernSchool/ServiceTests/PessoaServiceTests.cs
Labels: enhancement, code

#318 Melhorando os teste de escolas
  Codigo/ModernSchool/ModernSchoolWEBTests/Controllers/EscolaControllerTests.cs
  Codigo/ModernSchool/ServiceTests/EscolaServiceTests.cs
Labels: enhancement, code

#329 Removendo o cookie-bar no layout.cshtml. #328
  Codigo/ModernSchool/ModernSchool/Views/Shared/_Layout.cshtml
Labels: bug, enhancement, code
